{% set name = "napari-rembg" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-rembg-{{ version }}.tar.gz
  sha256: 2dc7a01279cf4b5044c96b66814cb1a22b715ec92fdef7cbe3d18308b6e6ff5c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=42.0.0
    - wheel
  run:
    - magicgui
    - napari >=0.4.16
    - numpy
    - pillow
    - python >=3.8
    - qtpy
    - rembg
    - scikit-image


test:
  imports:
    - napari_rembg
  commands:
    - pip list
    # - pip check  # Fails due to opencv-python-headless, which is a dependency of rembg
  requires:
    - pip
    - pyqt

about:
  home: https://pypi.org/project/napari-rembg
  summary: AI-based foreground extraction in scientific and natural images.
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/EPFL-Center-for-Imaging/napari-rembg

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - MalloryWittwer
